// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mermaid

import (
	"errors"
	"fmt"
)

const (
	// ASTNodeTypeDiagram is a ASTNodeType of type diagram.
	// Top-level diagram node
	ASTNodeTypeDiagram ASTNodeType = "diagram"
	// ASTNodeTypeDirection is a ASTNodeType of type direction.
	// Direction node
	ASTNodeTypeDirection ASTNodeType = "direction"
	// ASTNodeTypeStatedecl is a ASTNodeType of type statedecl.
	// State declaration
	ASTNodeTypeStatedecl ASTNodeType = "statedecl"
	// ASTNodeTypeTransition is a ASTNodeType of type transition.
	// Transition node
	ASTNodeTypeTransition ASTNodeType = "transition"
	// ASTNodeTypeNote is a ASTNodeType of type note.
	// Note node
	ASTNodeTypeNote ASTNodeType = "note"
	// ASTNodeTypeCompositeState is a ASTNodeType of type composite_state.
	// Composite state node
	ASTNodeTypeCompositeState ASTNodeType = "composite_state"
	// ASTNodeTypeComment is a ASTNodeType of type comment.
	// Comment node
	ASTNodeTypeComment ASTNodeType = "comment"
)

var ErrInvalidASTNodeType = errors.New("not a valid ASTNodeType")

// ASTNodeTypeValues returns a list of the values for ASTNodeType
func ASTNodeTypeValues() []ASTNodeType {
	return []ASTNodeType{
		ASTNodeTypeDiagram,
		ASTNodeTypeDirection,
		ASTNodeTypeStatedecl,
		ASTNodeTypeTransition,
		ASTNodeTypeNote,
		ASTNodeTypeCompositeState,
		ASTNodeTypeComment,
	}
}

// String implements the Stringer interface.
func (x ASTNodeType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ASTNodeType) IsValid() bool {
	_, err := ParseASTNodeType(string(x))
	return err == nil
}

var _ASTNodeTypeValue = map[string]ASTNodeType{
	"diagram":         ASTNodeTypeDiagram,
	"direction":       ASTNodeTypeDirection,
	"statedecl":       ASTNodeTypeStatedecl,
	"transition":      ASTNodeTypeTransition,
	"note":            ASTNodeTypeNote,
	"composite_state": ASTNodeTypeCompositeState,
	"comment":         ASTNodeTypeComment,
}

// ParseASTNodeType attempts to convert a string to a ASTNodeType.
func ParseASTNodeType(name string) (ASTNodeType, error) {
	if x, ok := _ASTNodeTypeValue[name]; ok {
		return x, nil
	}
	return ASTNodeType(""), fmt.Errorf("%s is %w", name, ErrInvalidASTNodeType)
}

// MarshalText implements the text marshaller method.
func (x ASTNodeType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ASTNodeType) UnmarshalText(text []byte) error {
	tmp, err := ParseASTNodeType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
