// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mermaid

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// HeaderTypeStateDiagramV1 is a HeaderType of type stateDiagramV1.
	HeaderTypeStateDiagramV1 HeaderType = "stateDiagram"
	// HeaderTypeStateDiagramV2 is a HeaderType of type stateDiagramV2.
	HeaderTypeStateDiagramV2 HeaderType = "stateDiagram-v2"
)

var ErrInvalidHeaderType = errors.New("not a valid HeaderType")

// HeaderTypeValues returns a list of the values for HeaderType
func HeaderTypeValues() []HeaderType {
	return []HeaderType{
		HeaderTypeStateDiagramV1,
		HeaderTypeStateDiagramV2,
	}
}

// String implements the Stringer interface.
func (x HeaderType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HeaderType) IsValid() bool {
	_, err := ParseHeaderType(string(x))
	return err == nil
}

var _HeaderTypeValue = map[string]HeaderType{
	"stateDiagram":    HeaderTypeStateDiagramV1,
	"statediagram":    HeaderTypeStateDiagramV1,
	"stateDiagram-v2": HeaderTypeStateDiagramV2,
	"statediagram-v2": HeaderTypeStateDiagramV2,
}

// ParseHeaderType attempts to convert a string to a HeaderType.
func ParseHeaderType(name string) (HeaderType, error) {
	if x, ok := _HeaderTypeValue[name]; ok {
		return x, nil
	}
	return HeaderType(""), fmt.Errorf("%s is %w", name, ErrInvalidHeaderType)
}

// MarshalText implements the text marshaller method.
func (x HeaderType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *HeaderType) UnmarshalText(text []byte) error {
	tmp, err := ParseHeaderType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// KeywordState is a Keyword of type state.
	KeywordState Keyword = "state"
	// KeywordDirection is a Keyword of type direction.
	KeywordDirection Keyword = "direction"
	// KeywordNote is a Keyword of type note.
	KeywordNote Keyword = "note"
	// KeywordAs is a Keyword of type as.
	KeywordAs Keyword = "as"
	// KeywordRight is a Keyword of type right.
	KeywordRight Keyword = "right"
	// KeywordLeft is a Keyword of type left.
	KeywordLeft Keyword = "left"
	// KeywordOf is a Keyword of type of.
	KeywordOf Keyword = "of"
	// KeywordConcurrent is a Keyword of type concurrent.
	KeywordConcurrent Keyword = "--"
	// KeywordColon is a Keyword of type colon.
	KeywordColon Keyword = ":"
	// KeywordArrow is a Keyword of type arrow.
	KeywordArrow Keyword = "-->"
	// KeywordFork is a Keyword of type fork.
	KeywordFork Keyword = "<<fork>>"
	// KeywordJoin is a Keyword of type join.
	KeywordJoin Keyword = "<<join>>"
	// KeywordChoice is a Keyword of type choice.
	KeywordChoice Keyword = "<<choice>>"
	// KeywordComment is a Keyword of type comment.
	KeywordComment Keyword = "%%"
	// KeywordBlockStart is a Keyword of type blockStart.
	KeywordBlockStart Keyword = "{"
	// KeywordBlockEnd is a Keyword of type blockEnd.
	KeywordBlockEnd Keyword = "}"
	// KeywordTerminalState is a Keyword of type terminalState.
	KeywordTerminalState Keyword = "[*]"
)

var ErrInvalidKeyword = errors.New("not a valid Keyword")

// KeywordValues returns a list of the values for Keyword
func KeywordValues() []Keyword {
	return []Keyword{
		KeywordState,
		KeywordDirection,
		KeywordNote,
		KeywordAs,
		KeywordRight,
		KeywordLeft,
		KeywordOf,
		KeywordConcurrent,
		KeywordColon,
		KeywordArrow,
		KeywordFork,
		KeywordJoin,
		KeywordChoice,
		KeywordComment,
		KeywordBlockStart,
		KeywordBlockEnd,
		KeywordTerminalState,
	}
}

// String implements the Stringer interface.
func (x Keyword) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Keyword) IsValid() bool {
	_, err := ParseKeyword(string(x))
	return err == nil
}

var _KeywordValue = map[string]Keyword{
	"state":      KeywordState,
	"direction":  KeywordDirection,
	"note":       KeywordNote,
	"as":         KeywordAs,
	"right":      KeywordRight,
	"left":       KeywordLeft,
	"of":         KeywordOf,
	"--":         KeywordConcurrent,
	":":          KeywordColon,
	"-->":        KeywordArrow,
	"<<fork>>":   KeywordFork,
	"<<join>>":   KeywordJoin,
	"<<choice>>": KeywordChoice,
	"%%":         KeywordComment,
	"{":          KeywordBlockStart,
	"}":          KeywordBlockEnd,
	"[*]":        KeywordTerminalState,
}

// ParseKeyword attempts to convert a string to a Keyword.
func ParseKeyword(name string) (Keyword, error) {
	if x, ok := _KeywordValue[name]; ok {
		return x, nil
	}
	return Keyword(""), fmt.Errorf("%s is %w", name, ErrInvalidKeyword)
}

// MarshalText implements the text marshaller method.
func (x Keyword) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Keyword) UnmarshalText(text []byte) error {
	tmp, err := ParseKeyword(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// TokenTypeKeyword is a TokenType of type Keyword.
	TokenTypeKeyword TokenType = iota
	// TokenTypeText is a TokenType of type Text.
	TokenTypeText
	// TokenTypeIdentifier is a TokenType of type Identifier.
	TokenTypeIdentifier
	// TokenTypeBlockStart is a TokenType of type BlockStart.
	TokenTypeBlockStart
	// TokenTypeBlockEnd is a TokenType of type BlockEnd.
	TokenTypeBlockEnd
	// TokenTypeEOF is a TokenType of type EOF.
	TokenTypeEOF
	// TokenTypeEOL is a TokenType of type EOL.
	TokenTypeEOL
)

var ErrInvalidTokenType = errors.New("not a valid TokenType")

const _TokenTypeName = "KeywordTextIdentifierBlockStartBlockEndEOFEOL"

// TokenTypeValues returns a list of the values for TokenType
func TokenTypeValues() []TokenType {
	return []TokenType{
		TokenTypeKeyword,
		TokenTypeText,
		TokenTypeIdentifier,
		TokenTypeBlockStart,
		TokenTypeBlockEnd,
		TokenTypeEOF,
		TokenTypeEOL,
	}
}

var _TokenTypeMap = map[TokenType]string{
	TokenTypeKeyword:    _TokenTypeName[0:7],
	TokenTypeText:       _TokenTypeName[7:11],
	TokenTypeIdentifier: _TokenTypeName[11:21],
	TokenTypeBlockStart: _TokenTypeName[21:31],
	TokenTypeBlockEnd:   _TokenTypeName[31:39],
	TokenTypeEOF:        _TokenTypeName[39:42],
	TokenTypeEOL:        _TokenTypeName[42:45],
}

// String implements the Stringer interface.
func (x TokenType) String() string {
	if str, ok := _TokenTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TokenType) IsValid() bool {
	_, ok := _TokenTypeMap[x]
	return ok
}

var _TokenTypeValue = map[string]TokenType{
	_TokenTypeName[0:7]:                    TokenTypeKeyword,
	strings.ToLower(_TokenTypeName[0:7]):   TokenTypeKeyword,
	_TokenTypeName[7:11]:                   TokenTypeText,
	strings.ToLower(_TokenTypeName[7:11]):  TokenTypeText,
	_TokenTypeName[11:21]:                  TokenTypeIdentifier,
	strings.ToLower(_TokenTypeName[11:21]): TokenTypeIdentifier,
	_TokenTypeName[21:31]:                  TokenTypeBlockStart,
	strings.ToLower(_TokenTypeName[21:31]): TokenTypeBlockStart,
	_TokenTypeName[31:39]:                  TokenTypeBlockEnd,
	strings.ToLower(_TokenTypeName[31:39]): TokenTypeBlockEnd,
	_TokenTypeName[39:42]:                  TokenTypeEOF,
	strings.ToLower(_TokenTypeName[39:42]): TokenTypeEOF,
	_TokenTypeName[42:45]:                  TokenTypeEOL,
	strings.ToLower(_TokenTypeName[42:45]): TokenTypeEOL,
}

// ParseTokenType attempts to convert a string to a TokenType.
func ParseTokenType(name string) (TokenType, error) {
	if x, ok := _TokenTypeValue[name]; ok {
		return x, nil
	}
	return TokenType(0), fmt.Errorf("%s is %w", name, ErrInvalidTokenType)
}

// MarshalText implements the text marshaller method.
func (x TokenType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TokenType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseTokenType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
