// Code generated by trifsm; DO NOT EDIT.
// Version: 
package generator

import (
    "github.com/looplab/fsm"
)

// Type alias for DoorFSM
type DoorFSM = string

// States
const (
    DoorFSMOpen DoorFSM = "open"
    DoorFSMClosed DoorFSM = "closed"
)

// Transition events
const (
    // Door closed now
    DoorFSMOpen__DoorFSMClosed DoorFSM = DoorFSMOpen+"__"+DoorFSMClosed
    // Door opened now
    DoorFSMClosed__DoorFSMOpen DoorFSM = DoorFSMClosed+"__"+DoorFSMOpen
)

func NewDoorFSM(callbacks fsm.Callbacks) *fsm.FSM {
	return fsm.NewFSM(
		DoorFSMOpen,
        	fsm.Events{
			{Name: DoorFSMOpen__DoorFSMClosed, Src: []string{DoorFSMOpen}, Dst: DoorFSMClosed},
			{Name: DoorFSMClosed__DoorFSMOpen, Src: []string{DoorFSMClosed}, Dst: DoorFSMOpen},
		},
		callbacks,
	)
}

