// Code generated by trifsm; DO NOT EDIT.
// Version: 
package generator

import (
    "github.com/looplab/fsm"
)

// Type alias for TrafficLightFSM
type TrafficLightFSM = string

// States
const (
    TrafficLightFSMGreen TrafficLightFSM = "green"
    TrafficLightFSMYellow TrafficLightFSM = "yellow"
    TrafficLightFSMRed TrafficLightFSM = "red"
)

// Transition events
const (
    // Proceed with caution
    TrafficLightFSMGreen__TrafficLightFSMYellow TrafficLightFSM = TrafficLightFSMGreen+"__"+TrafficLightFSMYellow
    // Stop
    TrafficLightFSMYellow__TrafficLightFSMRed TrafficLightFSM = TrafficLightFSMYellow+"__"+TrafficLightFSMRed
    // gogogo
    TrafficLightFSMRed__TrafficLightFSMGreen TrafficLightFSM = TrafficLightFSMRed+"__"+TrafficLightFSMGreen
)

func NewTrafficLightFSM(callbacks fsm.Callbacks) *fsm.FSM {
	return fsm.NewFSM(
		TrafficLightFSMGreen,
        	fsm.Events{
			{Name: TrafficLightFSMGreen__TrafficLightFSMYellow, Src: []string{TrafficLightFSMGreen}, Dst: TrafficLightFSMYellow},
			{Name: TrafficLightFSMYellow__TrafficLightFSMRed, Src: []string{TrafficLightFSMYellow}, Dst: TrafficLightFSMRed},
			{Name: TrafficLightFSMRed__TrafficLightFSMGreen, Src: []string{TrafficLightFSMRed}, Dst: TrafficLightFSMGreen},
		},
		callbacks,
	)
}

